# Config file template
#
# Uncomment, and replace, the item(s) with the value you wish to use.
# Configurations are alphabetically ordered within each section.

## ----- CONFIG FILE PATHS -----

# YAML file of your cluster's information
# (e.g. configuration/examples/cluster_info__demo.yaml).
cluster_info_file: "<cluster_info_file_path>"

# Dashboard users file (e.g., configuration/examples/user_list__demo.csv)
dashboard_users_file: "<dashboard_users_file_path>"

# The fixed parameters YAML file to use
# (e.g. ga_dashboard/data/fixed_parameters.yaml).
fixed_params_file: "<fixed_params_file_path>"


## ----- DATABASE CONFIG -----

# Machine (e.g. IP address) hosting your database (e.g. localhost).
db_host: "<db_host>"

# The name of the database to store your raw and enriched `sacct` data.
db_name: "ga_db"

# PostgreSQL host's port
db_port: 5432

# Script to create empty PostgreSQL database (database schema).
db_script: "ga_dashboard/database/ga_db.sql"

# The default database user (e.g. postgres).
db_user: "<db_user>"

# PostgreSQL version, e.g. 15 - to be filled once PostgreSQL is installed
pg_version: "<pg_version>"


## ----- GRAFANA CONFIG -----

# Grafana admin user name (e.g. admin).
admin_login: "<admin_login>"

# Name of the dashboard folder (on Grafana).
dashboard_folder_name: "Green Algorithms"

# Dashboard JSON files directory, on disk.
input_dir: "ga_dashboard/dashboards"

# Name of data source (on Grafana).
name: "grafana-postgresql-ga_db"

# Grafana URL, including port (e.g. localhost:3000).
url: "<url:port>"


## ----- RUN CONFIG -----

# Where to pull input logs from?
# Available input modes - sacct | file
input_mode: "<sacct or file>"

# If input_mode = 'file', specify the file path to the input logs
input_log_file_path: "<input_logs_path>"

# Set 'skip_db_overwrite: True' to stop overwriting the Database (if found) during Dashboard installation.
# This is for cases when the database exists and is already configured (i.e. contains the appropriate tables and user information), but the installation script needs to be run again for some reason.
# If using a Docker container, this must be set to True to avoid deletion/recreation of the database every time the Container starts.
skip_db_overwrite: False 


## ----- DEBUG CONFIG -----
# These configurations are used for code debugging or test runs

# Uncomment if you want to see debug output
# debug: true

# The last day to take into account by the sacct command on HPC (e.g. 2025-07-03).
# endDay: "<YYYY-MM-DD>"

# The start date passed to the `sacct` command (e.g. 2025-02-01).
# startDay: "<YYYY-MM-DD>"




