{
 "title": "User",
 "time": { "from": "2023-05-02T00:00:00.000Z", "to": "2023-06-30T00:00:00.000Z" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Green Algorithms Dashboard - User <span style=\"color:limegreen\">**${__user.login}**</span>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
   "options": {
    "content": "Computing is a major contributor to energy consumption, and thus is one of the main sources of the carbon emission of our research. In the\ncontext of the global climate crisis, it is imperative that individuals and organizations find ways to assess then reduce the carbon footprint of their\nwork.\n\nThis page aims to represent the carbon footprint that we are, collectively and individually, responsible for at University of .... SLURM jobs\nsubmitted to the CSD3 High Performance Cluster are logged automatically (including information such as resource requested, run time, memory\nefficiency, etc.), and the corresponding carbon footprint was calculated using the framework proposed by Green Algorithms and the following\nassumptions:\n\n| Type                      | Value                                             |\n| ------------------------- | ------------------------------------------------- | \n| CPU                       | 5.9 - 9.4 W/core (see here for models)            |\n| GPU                       | NVIDIA A100 (300 W) and NVIDIA Tesla P100 (250 W) |\n| Memory power              | 0.3725 W/GB                                       |\n| Power usage effectiveness | 1.15                                              |\n| Carbon intensity          | 231.12 gCO<sub>2</sub>e/kWh                                  |\n| Energy cost               | £0.34/kWh                                         |\n\n"
   },
   "targets": [
    {}
   ]
  },
  { "title": "Institution activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "💻  CPU time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(cpuhourscharged) FROM ga_data_aggregate LIMIT 50 "
    }
   ]
  },
  {
   "title": "👣  Carbon footprint",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kgCO2e" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(carbonfootprint) FROM ga_data_aggregate LIMIT 50 "
    }
   ]
  },
  {
   "title": "🌳  Carbon sequestration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "tree-years" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(treemonths)/12 FROM ga_data_aggregate;"
    }
   ]
  },
  {
   "title": "✈️  New York - San Francisco",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(flying_ny_sf) FROM ga_data_aggregate LIMIT 50 "
    }
   ]
  },
  {
   "title": "Daily carbon footprint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT submitdate, SUM(carbonfootprint) FROM ga_data_aggregate GROUP BY submitdate ORDER BY submitdate ASC "
    }
   ]
  },
  {
   "title": "⚡ Energy distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(energy_cpus) as \"CPUS\", SUM(energy_gpus) as \"GPUS\", SUM(energy_memory) as \"Memory\", SUM(energy-(energy_cpus+energy_gpus+energy_memory)) as \"Other\" FROM ga_data_aggregate ORDER BY SUM(energy_cpus) "
    }
   ]
  },
  {
   "title": "Distribution Failed vs Successful jobs",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(n_jobs-n_success) AS \"Failed jobs\", SUM(n_success) AS \"Successful jobs\" FROM ga_data_aggregate ORDER BY SUM(n_jobs-n_success) ASC "
    }
   ]
  },
  {
   "title": "User activity - ${__user.login}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "💻  CPU time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(cpuhourscharged) FROM ga_data_aggregate WHERE user_name = '${__user.login}' LIMIT 50 "
    }
   ]
  },
  {
   "title": "👣  Carbon footprint",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(carbonfootprint) FROM ga_data_aggregate WHERE user_name = '${__user.login}' LIMIT 50 "
    }
   ]
  },
  {
   "title": "🌳  Carbon sequestration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "tree-years" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(treemonths)/12 FROM ga_data_aggregate WHERE user_name='${__user.login}';"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(flying_par_lon) FROM ga_data_aggregate WHERE user_name = '${__user.login}' LIMIT 50 "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(flying_ny_sf) FROM ga_data_aggregate WHERE user_name = '${__user.login}' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Daily carbon footprint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT submitdate, SUM(carbonfootprint) FROM ga_data_aggregate WHERE user_name = '${__user.login}' GROUP BY submitdate ORDER BY submitdate "
    }
   ]
  },
  {
   "title": "Number of jobs started",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT submitdate, SUM(n_jobs) FROM ga_data_aggregate WHERE user_name = '${__user.login}' GROUP BY submitdate ORDER BY submitdate "
    }
   ]
  },
  {
   "title": "CPU core hours charged",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "rawSql": "SELECT submitdate, SUM(cpuhourscharged) FROM ga_data_aggregate WHERE user_name = '${__user.login}' GROUP BY submitdate ORDER BY submitdate "
    }
   ]
  },
  {
   "title": "Memory requested",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "rawSql": "SELECT submitdate, SUM(memoryrequested) FROM ga_data_aggregate WHERE user_name = '${__user.login}' GROUP BY submitdate ORDER BY submitdate "
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 47 }, "options": { "content": "\n# Efficiency metrics" } },
  {
   "title": "Distribution Failed vs Successful jobs",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(n_jobs-n_success) AS \"Failed jobs\", SUM(n_success) AS \"Successful jobs\" FROM ga_data_aggregate WHERE user_name='${__user.login}' ORDER BY SUM(n_jobs-n_success) ASC "
    }
   ]
  },
  {
   "title": "Distribution Failed vs Successful jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 49 },
   "targets": [
    {
     "rawSql": "SELECT submitdate, (SUM(n_jobs-n_success)::float/SUM(n_jobs))*100 AS \"Failed jobs\",  (SUM(n_success)::float/SUM(n_jobs))*100 AS \"Successful jobs\" FROM ga_data_aggregate WHERE user_name='${__user.login}' GROUP BY submitdate ORDER BY submitdate; "
    }
   ]
  },
  {
   "title": "⚡ Energy distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(energy_cpus) as \"CPUS\", SUM(energy_gpus) as \"GPUS\", SUM(energy_memory) as \"Memory\", SUM(energy-(energy_cpus+energy_gpus+energy_memory)) as \"Other\" FROM ga_data_aggregate WHERE user_name='${__user.login}' ORDER BY SUM(energy_cpus) "
    }
   ]
  },
  {
   "title": "Memory efficiency",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 57 },
   "targets": [
    {
     "rawSql": "select r.range as \"Memory efficiency (%)\", SUM(n_jobs) as \"number of jobs\"\nfrom \n    (\n    select '0-4' as range, 4 as endrange\n\t\t\tunion all select '5-9',9\n\t    union all select '10-14',14\n\t    union all select '15-19',19\n\t    union all select '20-24',24\n\t    union all select '25-29',29\n\t    union all select '30-34',34\n\t    union all select '35-39',39\n\t    union all select '40-44',44\n\t    union all select '45-49',49\n\t    union all select '50-54',54\n\t    union all select '55-59',59\n\t    union all select '60-64',64\n\t    union all select '65-69',69\n\t    union all select '70-74',74\n\t    union all select '75-79',79\n\t    union all select '80-84',84\n\t    union all select '85-89',89\n\t    union all select '90-94',94\n\t\t\tunion all select '95-99',99\n\t\t\tunion all select '100',100\n    ) as r\nleft join ga_data_aggregate on \n    r.endrange = case \n\t\t\twhen ROUND((1/memoryoverallocationfactor)*100) = 100 then 100\n\t\t\twhen ROUND((1/memoryoverallocationfactor)*100) > 95 then 99\n\t    when ROUND((1/memoryoverallocationfactor)*100) > 90 then 94\n\t    when ROUND((1/memoryoverallocationfactor)*100) > 85 then 89\n\t    when ROUND((1/memoryoverallocationfactor)*100) > 80 then 84\n\t    when ROUND((1/memoryoverallocationfactor)*100) > 75 then 79\n\t    when ROUND((1/memoryoverallocationfactor)*100) > 70 then 74\n\t    when ROUND((1/memoryoverallocationfactor)*100) > 65 then 69\n\t    when ROUND((1/memoryoverallocationfactor)*100) > 60 then 64\n\t    when ROUND((1/memoryoverallocationfactor)*100) > 55 then 59\n\t    when ROUND((1/memoryoverallocationfactor)*100) > 50 then 54\n\t\t\twhen ROUND((1/memoryoverallocationfactor)*100) > 45 then 49\n\t    when ROUND((1/memoryoverallocationfactor)*100) > 40 then 44\n\t    when ROUND((1/memoryoverallocationfactor)*100) > 35 then 39\n\t    when ROUND((1/memoryoverallocationfactor)*100) > 30 then 34\n\t    when ROUND((1/memoryoverallocationfactor)*100) > 25 then 29\n\t    when ROUND((1/memoryoverallocationfactor)*100) > 20 then 24\n\t    when ROUND((1/memoryoverallocationfactor)*100) > 15 then 19\n\t    when ROUND((1/memoryoverallocationfactor)*100) > 10 then 14\n\t    when ROUND((1/memoryoverallocationfactor)*100) > 5 then 9\n\t\t\twhen ROUND((1/memoryoverallocationfactor)*100) >= 0 then 4\n    end\n\t\tWHERE user_name='${__user.login}'\ngroup by r.range,r.endrange order by r.endrange"
    }
   ]
  }
 ]
}