CREATE TABLE ga_data_aggregate (
	id SERIAL PRIMARY KEY,
	user_name VARCHAR(255),
	uid INTEGER,
	name VARCHAR(255),
	group_name VARCHAR(255),
	department VARCHAR(255),
	submitdate DATE,
	n_jobs INTEGER,
	first_job_period DATE,
	last_job_period DATE,
	energy DOUBLE PRECISION,
	energy_cpus DOUBLE PRECISION,
	energy_gpus DOUBLE PRECISION,
	energy_memory DOUBLE PRECISION,
	carbonfootprint DOUBLE PRECISION,
	carbonfootprint_memoryneededonly DOUBLE PRECISION,
	carbonfootprint_failedjobs DOUBLE PRECISION,
	cputime VARCHAR(255),
	gputime VARCHAR(255),
    wallclocktime VARCHAR(255),
	cpuhourscharged DOUBLE PRECISION,
	gpuhourscharged DOUBLE PRECISION,
	memoryrequested DOUBLE PRECISION,
	memoryoverallocationfactor DOUBLE PRECISION,
	n_success INTEGER,
	treemonths DOUBLE PRECISION,
	treemonths_memoryneededonly DOUBLE PRECISION,
	treemonths_failedjobs DOUBLE PRECISION,
	driving DOUBLE PRECISION,
	flying_ny_sf DOUBLE PRECISION,
	flying_par_lon DOUBLE PRECISION,
	flying_nyc_mel DOUBLE PRECISION,
	cost DOUBLE PRECISION,
	cost_failedjobs DOUBLE PRECISION,
	cost_memoryneededonly DOUBLE PRECISION,
	success_rate DOUBLE PRECISION,
	failure_rate DOUBLE PRECISION,
	share_carbonfootprint DOUBLE PRECISION
);
