{
 "title": "Green Algorithms Demo dashboard",
 "time": { "from": "2023-05-02T00:00:00.000Z", "to": "2023-06-20T00:00:00.000Z" },
 "templating": {
  "list": [
   { "name": "FILL_OPACITY", "label": "Fill opacity", "query": "10,20,50,100" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "description": "dddd",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Institution Activity\n\nOverall activity at <institution> between <start date> and <end date>.\n"
   }
  },
  {
   "title": "Daily total HPC carbon footprint (all departments)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT submitdate, SUM(carbonfootprint) FROM ga_data_aggregate GROUP BY submitdate ORDER BY submitdate "
    }
   ]
  },
  {
   "title": "Daily total number of jobs submitted (all departments)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT submitdate, SUM(n_jobs) FROM ga_data_aggregate GROUP BY submitdate ORDER BY submitdate "
    }
   ]
  },
  {
   "title": "CPU core-hours",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT submitdate, SUM(cpuhourscharged) FROM ga_data_aggregate GROUP BY submitdate ORDER BY submitdate ASC "
    }
   ]
  },
  {
   "title": "Memory requested ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT submitdate, SUM(memoryrequested) FROM ga_data_aggregate GROUP BY submitdate ORDER BY submitdate "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 21 },
   "options": {
    "content": "# Departments\n\nCarbon footprint of all departments between <start date> and <end date>.\n"
   }
  },
  {
   "title": "Daily carbon footprint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT submitdate, SUM(carbonfootprint) AS \"CFP\", department \nFROM\n\t(SELECT d.submitdate, u.department, d.carbonfootprint \n\tFROM\n\tga_user u INNER JOIN ga_data_aggregate d ON u.user_name = d.user_name)\nGROUP BY\nsubmitdate, department;"
    }
   ]
  },
  {
   "title": "Main contributors to the total carbon footprint",
   "type": "barchart",
   "description": "Carbon footprint of all departments between <start date> and <end-date>",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT department, SUM(carbonfootprint) FROM (select u.user_name, u.department, d.carbonfootprint from ga_user u INNER JOIN ga_data_aggregate d on u.user_name = d.user_name) GROUP BY department ORDER BY SUM(carbonfootprint) DESC;"
    }
   ]
  }
 ]
}