{
 "title": "Group",
 "description": "Computing is a major contributor to energy consumption, and thus is one of the main sources of the carbon emission of our research. In the\ncontext of the global climate crisis, it is imperative that individuals and organizations find ways to assess then reduce the carbon footprint of their\nwork.\nThis page aims to represent the carbon footprint that we are, collectively and individually, responsible for at University of .... SLURM jobs\nsubmitted to the CSD3 High Performance Cluster are logged automatically (including information such as resource requested, run time, memory\nefficiency, etc.), and the corresponding carbon footprint was calculated using the framework proposed by Green Algorithms and the following\nassumptions:\nCPU 5.9 - 9.4 W/core (see here for models)\nGPU NVIDIA A100 (300 W) and NVIDIA Tesla P100 (250 W)\nMemory power 0.3725 W/GB\nPower usage effectiveness 1.15\nCarbon intensity 231.12 gCO e/kWh\nEnergy cost £0.34/kWh",
 "time": { "from": "2023-05-02T00:00:00.000Z", "to": "2023-06-30T00:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "current_users_department",
    "query": "SELECT distinct department from ga_user where user_name='${__user.login}' limit 1;"
   },
   {
    "name": "current_users_group",
    "query": "SELECT distinct group_name from ga_user where user_name='${__user.login}' limit 1;"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Green Algorithms Dashboard \n\n## Department: <span style=\"color:dodgerblue\">**${current_users_department}**</span> | Group: <span style=\"color:gold\">**${current_users_group}**</span>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 3 },
   "options": {
    "content": "Computing is a major contributor to energy consumption, and thus is one of the main sources of the carbon emission of our research. In the\ncontext of the global climate crisis, it is imperative that individuals and organizations find ways to assess then reduce the carbon footprint of their\nwork.\n\nThis page aims to represent the carbon footprint that we are, collectively and individually, responsible for at University of .... SLURM jobs\nsubmitted to the CSD3 High Performance Cluster are logged automatically (including information such as resource requested, run time, memory\nefficiency, etc.), and the corresponding carbon footprint was calculated using the framework proposed by Green Algorithms and the following\nassumptions:\n\n| Type                      | Value                                             |\n| ------------------------- | ------------------------------------------------- | \n| CPU                       | 5.9 - 9.4 W/core (see here for models)            |\n| GPU                       | NVIDIA A100 (300 W) and NVIDIA Tesla P100 (250 W) |\n| Memory power              | 0.3725 W/GB                                       |\n| Power usage effectiveness | 1.15                                              |\n| Carbon intensity          | 231.12 gCO<sub>2</sub>e/kWh                                  |\n| Energy cost               | £0.34/kWh                                         |\n\n"
   }
  },
  { "title": "Institution activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 15 },
   "options": {
    "content": "Overall activity of the institution\n"
   }
  },
  {
   "title": "💻  CPU time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(cpuhourscharged) FROM ga_data_aggregate LIMIT 50 "
    }
   ]
  },
  {
   "title": "👣  Carbon footprint",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kgCO2e" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(carbonfootprint) FROM ga_data_aggregate LIMIT 50 "
    }
   ]
  },
  {
   "title": "✈️  New York - San Francisco",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(flying_ny_sf) FROM ga_data_aggregate LIMIT 50 "
    }
   ]
  },
  {
   "title": "🌳  Carbon sequestration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "tree-years" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(treemonths)/12 FROM ga_data_aggregate;"
    }
   ]
  },
  {
   "title": "Daily carbon footprint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT submitdate, SUM(carbonfootprint) FROM ga_data_aggregate GROUP BY submitdate ORDER BY submitdate ASC "
    }
   ]
  },
  {
   "title": "Number of jobs started",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT submitdate, SUM(n_jobs) FROM ga_data_aggregate GROUP BY submitdate ORDER BY submitdate ASC "
    }
   ]
  },
  {
   "title": "CPU core hours charged",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT submitdate, SUM(cpuhourscharged) FROM ga_data_aggregate GROUP BY submitdate ORDER BY submitdate ASC "
    }
   ]
  },
  {
   "title": "Memory requested",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "rawSql": "SELECT submitdate, SUM(memoryrequested) FROM ga_data_aggregate GROUP BY submitdate ORDER BY submitdate ASC "
    }
   ]
  },
  {
   "title": "⚡ Energy distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(energy_cpus) as \"CPUS\", SUM(energy_gpus) as \"GPUS\", SUM(energy_memory) as \"Memory\", SUM(energy-(energy_cpus+energy_gpus+energy_memory)) as \"Other\" FROM ga_data_aggregate ORDER BY SUM(energy_cpus) "
    }
   ]
  },
  { "title": "Departments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 47 },
   "options": {
    "content": "Carbon footprint of all departments\n\n"
   }
  },
  {
   "title": "Main contributors to the total carbon footprint",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "rawSql": "SELECT department, SUM(carbonfootprint) FROM (select u.user_name, u.department, d.carbonfootprint from ga_user u INNER JOIN ga_data_aggregate d on u.user_name = d.user_name) GROUP BY department ORDER BY department ASC;\n"
    }
   ]
  },
  {
   "title": "Daily carbon footprint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "rawSql": "SELECT submitdate, SUM(carbonfootprint) AS \"CFP\", department\nFROM\n(SELECT d.submitdate, u.department, d.carbonfootprint FROM ga_user u INNER JOIN ga_data_aggregate d ON u.user_name = d.user_name)\nGROUP BY submitdate, department"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "rawSql": "SELECT department AS \"Department\", SUM(carbonfootprint) AS \"Carbon footprint\", SUM(cost) AS \"Cost\"\nFROM\n(SELECT u.department, d.carbonfootprint, d.cost FROM ga_user u INNER JOIN ga_data_aggregate d ON u.user_name = d.user_name)\nGROUP BY department ORDER BY department ASC ;"
    }
   ]
  },
  { "title": "Efficiency metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Distribution Failed vs Successful jobs",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(n_jobs-n_success) AS \"Failed jobs\", SUM(n_success) AS \"Successful jobs\" FROM ga_data_aggregate ORDER BY SUM(n_jobs-n_success) ASC "
    }
   ]
  },
  {
   "title": "Distribution Failed vs Successful jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "rawSql": "SELECT submitdate, (SUM(n_jobs-n_success)::float/SUM(n_jobs))*100 AS \"Failed jobs\",  (SUM(n_success)::float/SUM(n_jobs))*100 AS \"Successful jobs\" FROM ga_data_aggregate GROUP BY submitdate ORDER BY submitdate; \n"
    }
   ]
  },
  {
   "title": "Memory efficiency",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "rawSql": "select r.range as \"Memory efficiency (%)\", SUM(n_jobs) as \"number of jobs\"\nfrom \n    (\n    select '0-4' as range, 4 as endrange\n\t\t\tunion all select '5-9',9\n\t    union all select '10-14',14\n\t    union all select '15-19',19\n\t    union all select '20-24',24\n\t    union all select '25-29',29\n\t    union all select '30-34',34\n\t    union all select '35-39',39\n\t    union all select '40-44',44\n\t    union all select '45-49',49\n\t    union all select '50-54',54\n\t    union all select '55-59',59\n\t    union all select '60-64',64\n\t    union all select '65-69',69\n\t    union all select '70-74',74\n\t    union all select '75-79',79\n\t    union all select '80-84',84\n\t    union all select '85-89',89\n\t    union all select '90-94',94\n\t\t\tunion all select '95-99',99\n\t\t\tunion all select '100',100\n    ) as r\nleft join ga_data_aggregate on \n    r.endrange = case \n\t\t\twhen ROUND((1/memoryoverallocationfactor)*100) = 100 then 100\n\t\t\twhen ROUND((1/memoryoverallocationfactor)*100) > 95 then 99\n\t    when ROUND((1/memoryoverallocationfactor)*100) > 90 then 94\n\t    when ROUND((1/memoryoverallocationfactor)*100) > 85 then 89\n\t    when ROUND((1/memoryoverallocationfactor)*100) > 80 then 84\n\t    when ROUND((1/memoryoverallocationfactor)*100) > 75 then 79\n\t    when ROUND((1/memoryoverallocationfactor)*100) > 70 then 74\n\t    when ROUND((1/memoryoverallocationfactor)*100) > 65 then 69\n\t    when ROUND((1/memoryoverallocationfactor)*100) > 60 then 64\n\t    when ROUND((1/memoryoverallocationfactor)*100) > 55 then 59\n\t    when ROUND((1/memoryoverallocationfactor)*100) > 50 then 54\n\t\t\twhen ROUND((1/memoryoverallocationfactor)*100) > 45 then 49\n\t    when ROUND((1/memoryoverallocationfactor)*100) > 40 then 44\n\t    when ROUND((1/memoryoverallocationfactor)*100) > 35 then 39\n\t    when ROUND((1/memoryoverallocationfactor)*100) > 30 then 34\n\t    when ROUND((1/memoryoverallocationfactor)*100) > 25 then 29\n\t    when ROUND((1/memoryoverallocationfactor)*100) > 20 then 24\n\t    when ROUND((1/memoryoverallocationfactor)*100) > 15 then 19\n\t    when ROUND((1/memoryoverallocationfactor)*100) > 10 then 14\n\t    when ROUND((1/memoryoverallocationfactor)*100) > 5 then 9\n\t\t\twhen ROUND((1/memoryoverallocationfactor)*100) >= 0 then 4\n    end\ngroup by r.range,r.endrange order by r.endrange"
    }
   ]
  },
  {
   "title": "Groups in your department ($current_users_department)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 }
  },
  {
   "title": "Groups in your department ($current_users_department)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "targets": [
    {
     "rawSql": "SELECT submitdate, SUM(carbonfootprint) AS \"CFP\", group_name\nFROM (SELECT u.group_name, d.submitdate, d.carbonfootprint FROM ga_user u INNER JOIN ga_data_aggregate d ON u.user_name = d.user_name WHERE u.department = '$current_users_department')\nGROUP BY submitdate, group_name\nORDER BY group_name ASC LIMIT null ;"
    }
   ]
  },
  {
   "title": "Groups in your department ($current_users_department)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "targets": [
    {
     "rawSql": "SELECT group_name AS \"Group\", to_char(SUM(carbonfootprint)/1000, '9999999') AS \"Carbon footprint (kgCO2e)\", SUM(cost) AS \"Cost (£)\"\nFROM \n(SELECT u.user_name, u.group_name, d.carbonfootprint, d.cost FROM ga_user u INNER JOIN ga_data_aggregate d ON u.user_name = d.user_name WHERE u.department = '$current_users_department')\nGROUP BY group_name \nORDER BY group_name ASC;"
    }
   ]
  },
  {
   "title": "Users in your group ($current_users_group)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 }
  },
  {
   "title": "Users in your group ($current_users_group)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "targets": [
    {
     "rawSql": "SELECT submitdate, SUM(carbonfootprint) AS \"CFP\", user_name\nFROM \n(SELECT u.user_name, d.submitdate, d.carbonfootprint FROM ga_user u INNER JOIN ga_data_aggregate d ON u.user_name = d.user_name WHERE u.group_name = '$current_users_group')\nGROUP BY submitdate, user_name \nORDER BY user_name ;"
    }
   ]
  },
  {
   "title": "Users in your group ($current_users_group)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "targets": [
    {
     "rawSql": "SELECT user_name AS \"User name\", name AS \"Name\", to_char(SUM(carbonfootprint)/1000, '9999999') AS \"Carbon footprint (kgCO2e)\", SUM(cost) AS \"Cost (£)\" \nFROM \n(SELECT u.user_name, u.name, d.carbonfootprint, d.cost FROM ga_user u INNER JOIN ga_data_aggregate d ON u.user_name = d.user_name WHERE u.group_name = '$current_users_group')\nGROUP BY user_name, name \nORDER BY user_name;"
    }
   ]
  }
 ]
}