{
 "title": "User",
 "time": { "from": "now-90d", "to": "now-1d/d" },
 "templating": {
  "list": [
   {
    "name": "user_name",
    "label": "User",
    "query": "SELECT name FROM ga_user WHERE user_name = '${__user.login}'"
   },
   {
    "name": "group_name",
    "query": "SELECT group_name FROM ga_user WHERE user_name = '${__user.login}'"
   },
   {
    "name": "department",
    "query": "SELECT department FROM ga_user WHERE user_name = '${__user.login}'"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "description": "Introductory panel.",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# 🌱 Green Algorithms Dashboard\n---\n\n"
   }
  },
  {
   "type": "text",
   "description": "Introductory panel.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 2 },
   "options": {
    "content": "Computing is a major contributor to energy consumption, and thus is one of the main sources of the carbon emission of our research. In the\ncontext of the global climate crisis, it is imperative that individuals and organizations find ways to assess, then reduce, the carbon footprint of their\nwork.\nThis page aims to represent the carbon footprint that we are, collectively and individually, responsible for at the institution.\n SLURM jobs\nsubmitted to High Performance Clusters are logged automatically (including information such as resource requested, run time, memory\nefficiency, etc.), and the corresponding carbon footprint was calculated using the framework proposed by [Green Algorithms](https://www.green-algorithms.org) and the following assumptions:\n\n|Type|Value|\n|----|-----|\n|CPU |5.9 - 9.4 W/core|\n|GPU |NVIDIA A100 (300 W) and NVIDIA Tesla P100 (250 W)|\n|Memory power | 0.3725 W/GB|\n|Power usage effectiveness| 1.15|\n|Carbon intensity |231.12 gCO<sub>2</sub> e/kWh|\n|Energy cost| £0.34/kWh|\n\n\nWe built this tool in the hope of raising awareness of computing usage, highlighting resource waste, and fostering good computing practices. This\nis intended to be a lightweight carbon footprint calculator, not a cluster monitoring system.\n"
   }
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  { "title": "Your activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 15 },
   "options": {
    "content": "# Report for user <span style=\"color:#5794F2\">$user_name</span>\n\nFind out your carbon footprint for the time period selected (see date panel at top)."
   }
  },
  {
   "title": "💻 CPU time",
   "type": "stat",
   "description": "Unit: weeks, months or years",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(cpuhourscharged) FROM ga_data_aggregate where user_name = '${__user.login}' AND $__timeFilter(submitdate);"
    }
   ]
  },
  {
   "title": "👣  Carbon footprint",
   "type": "stat",
   "description": "Unit:  gCO2e or kgCO2e",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(carbonfootprint) FROM ga_data_aggregate where user_name='${__user.login}' AND $__timeFilter(submitdate);"
    }
   ]
  },
  {
   "title": "✈️  New York - San Francisco",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(flying_ny_sf) FROM ga_data_aggregate WHERE user_name = '${__user.login}' AND $__timeFilter(submitdate);"
    }
   ]
  },
  {
   "title": "✈️  Paris - London",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 13, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(flying_par_lon) FROM ga_data_aggregate WHERE user_name = '${__user.login}' AND $__timeFilter(submitdate);"
    }
   ]
  },
  {
   "title": "🌳 Carbon sequestration",
   "type": "stat",
   "description": "Unit: tree-years",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "tree-years" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(treemonths)/12 FROM ga_data_aggregate WHERE user_name = '${__user.login}' AND $__timeFilter(submitdate);"
    }
   ]
  },
  {
   "title": "User's daily total HPC carbon footprint",
   "type": "timeseries",
   "description": "Unit: gCO2e or kgCO2e",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT a.submitdate, SUM(a.carbonfootprint) FROM (SELECT d.submitdate, d.carbonfootprint FROM ga_user u INNER JOIN ga_data_aggregate d ON u.user_name = d.user_name WHERE u.user_name = '${__user.login}') AS a GROUP BY a.submitdate ORDER BY a.submitdate ASC"
    }
   ]
  },
  {
   "title": "Daily total number of jobs submitted by user",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT n_jobs, submitdate FROM ga_data_aggregate WHERE user_name = '${__user.login}' ORDER BY submitdate ASC;"
    }
   ]
  },
  {
   "title": "User's CPU core-hours",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT submitdate, SUM(cpuhourscharged) FROM ga_data_aggregate WHERE user_name = '${__user.login}' GROUP BY submitdate ORDER BY submitdate ASC ;"
    }
   ]
  },
  {
   "title": "Memory requested by user",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT submitdate, SUM(memoryrequested) FROM ga_data_aggregate WHERE user_name = '${__user.login}' GROUP BY submitdate ORDER BY submitdate ASC;"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 42 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 44 },
   "options": {
    "content": "### # Efficiency metrics: Failed jobs (user <span style=\"color:#5794F2\">$user_name</span>)\nBecause any resource spent on a job is wasted if the job fails, it is important to test scripts and pipelines on small datasets. The chart below\nshows the daily success and failure rates of jobs that completed in the time period selected (see date panel at top).\n\n"
   }
  },
  {
   "title": "Cost of user's failed jobs",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "rawSql": "SELECT SUM(n_jobs) AS \"No. of jobs completed\", to_char(SUM(carbonfootprint_failedjobs)/1000,'99999999.99') AS \"Failed jobs' footprint (kgCO2e)\", to_char(SUM(cost_failedjobs), '9999999') AS \"Cost of failed jobs\", to_char((SUM(n_jobs-n_success)::float/SUM(n_jobs))*100, '999.99') AS \"% of failed jobs\" FROM ga_data_aggregate WHERE user_name = '${__user.login}' AND $__timeFilter(submitdate);"
    }
   ]
  },
  {
   "title": "User's distribution of failed jobs",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "rawSql": "SELECT submitdate, (SUM(n_jobs-n_success)::float/SUM(n_jobs))*100 AS \"Failed jobs\",  (SUM(n_success)::float/SUM(n_jobs))*100 AS \"Successful jobs\" FROM ga_data_aggregate WHERE user_name = '${__user.login}' GROUP BY submitdate ORDER BY submitdate ASC;"
    }
   ]
  },
  {
   "title": "User's total number of jobs submitted",
   "type": "stat",
   "description": "Number of jobs submitted by user in time period selected (see date panel at top).",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(n_jobs) AS \"Number of jobs for user ${__user.login}\" \nFROM ga_data_aggregate\nWHERE user_name = '${__user.login}' AND $__timeFilter(submitdate);"
    }
   ]
  },
  {
   "title": "User's distribution of failed and successful jobs",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(n_jobs-n_success) AS \"Failed jobs\", SUM(n_success) AS \"Successful jobs\" FROM ga_data_aggregate WHERE user_name = '${__user.login}' AND $__timeFilter(submitdate)ORDER BY SUM(n_jobs-n_success) ASC ;"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 59 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 61 },
   "options": {
    "content": "### # Memory efficiency (user <span style=\"color:#5794F2\">$user_name</span>)\n\nMemory can be a significant source of waste, because the power draw from memory mainly depends on the memory available, not on the actual\nmemory used. The chart below shows the distribution of the memory efficiency (the closer to 100% the better) collected from all this user's jobs in the period chosen (see date panel at top)."
   }
  },
  {
   "title": "User's % memory efficiency distribution",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT r.range as \"Memory efficiency (%)\", SUM(n_jobs) as \"Number of jobs\"\nfrom \n(\n    select '0-4' as range, 4 as endrange\n        union all select '5-9', 9\n        union all select '10-14', 14\n        union all select '15-19', 19\n        union all select '20-24', 24\n        union all select '25-29', 29\n        union all select '30-34', 34\n        union all select '35-39', 39\n        union all select '40-44', 44\n        union all select '45-49', 49\n        union all select '50-54', 54\n        union all select '55-59', 59\n        union all select '60-64', 64\n        union all select '65-69', 69\n        union all select '70-74', 74\n        union all select '75-79', 79\n        union all select '80-84', 84\n        union all select '85-89', 89\n        union all select '90-94', 94\n        union all select '95-99', 99\n        union all select '100', 100\n) as r\nleft join ga_data_aggregate on \nr.endrange = case \n    when ROUND((1/memoryoverallocationfactor)*100) = 100 then 100\n    when ROUND((1/memoryoverallocationfactor)*100) > 95 then 99\n    when ROUND((1/memoryoverallocationfactor)*100) > 90 then 94\n    when ROUND((1/memoryoverallocationfactor)*100) > 85 then 89\n    when ROUND((1/memoryoverallocationfactor)*100) > 80 then 84\n    when ROUND((1/memoryoverallocationfactor)*100) > 75 then 79\n    when ROUND((1/memoryoverallocationfactor)*100) > 70 then 74\n    when ROUND((1/memoryoverallocationfactor)*100) > 65 then 69\n    when ROUND((1/memoryoverallocationfactor)*100) > 60 then 64\n    when ROUND((1/memoryoverallocationfactor)*100) > 55 then 59\n    when ROUND((1/memoryoverallocationfactor)*100) > 50 then 54\n    when ROUND((1/memoryoverallocationfactor)*100) > 45 then 49\n    when ROUND((1/memoryoverallocationfactor)*100) > 40 then 44\n    when ROUND((1/memoryoverallocationfactor)*100) > 35 then 39\n    when ROUND((1/memoryoverallocationfactor)*100) > 30 then 34\n    when ROUND((1/memoryoverallocationfactor)*100) > 25 then 29\n    when ROUND((1/memoryoverallocationfactor)*100) > 20 then 24\n    when ROUND((1/memoryoverallocationfactor)*100) > 15 then 19\n    when ROUND((1/memoryoverallocationfactor)*100) > 10 then 14\n    when ROUND((1/memoryoverallocationfactor)*100) > 5 then 9\n    when ROUND((1/memoryoverallocationfactor)*100) >= 0 then 4\n    end\n    WHERE user_name='${__user.login}' AND $__timeFilter(submitdate)\n    group by r.range, r.endrange order by r.endrange;\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Your group's activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 75 },
     "options": {
      "content": "## Carbon footprint for the users in your group ($group_name)\nCarbon footprint of all users in your group ($group_name) in the time range specified."
     }
    },
    {
     "title": "Carbon footprints of users in your group ($group_name)",
     "type": "timeseries",
     "description": "Unit: gCO2e or kgCO2e",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
     "targets": [
      {
       "rawSql": "SELECT a.submitdate, SUM(a.carbonfootprint) AS \"Carbon footprint of\", a.name\nFROM\n(SELECT d.submitdate, u.name, d.carbonfootprint FROM ga_user u INNER JOIN ga_data_aggregate d ON u.user_name = d.user_name WHERE u.group_name = '$group_name') AS a\nGROUP BY\na.submitdate, a.name;"
      }
     ]
    },
    {
     "title": "Contribution of users to the carbon footprint of your group ($group_name)",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
     "targets": [
      {
       "rawSql": "SELECT a.user_name AS \"Username\", a.name AS \"Name\", to_char(SUM(carbonfootprint)/1000, '9999999') AS \"Carbon footprint (kgCO2e)\", to_char(SUM(a.cost), '9999') AS \"Cost\"\nFROM\n(SELECT u.user_name, u.name, d.carbonfootprint, d.cost FROM ga_user u INNER JOIN ga_data_aggregate d ON u.user_name = d.user_name WHERE u.group_name = '$group_name' AND $__timeFilter(d.submitdate)) AS a\nGROUP BY a.user_name, a.name\nORDER BY a.user_name;"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 158 } }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Your department's activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 317 },
     "options": {
      "content": "## Carbon footprint for the groups in your department ($department)\nCarbon footprint of all groups in your department in the time range specified (see date panel at top)."
     }
    },
    {
     "title": "Carbon footprint of groups in your department ($department)",
     "type": "timeseries",
     "description": "Unit: gCO2e or kgCO2e",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 320 },
     "targets": [
      {
       "rawSql": "SELECT a.submitdate, SUM(a.carbonfootprint) AS \"Carbon footprint of\", a.group_name\nFROM\n(SELECT d.submitdate, u.group_name, d.carbonfootprint FROM ga_user u INNER JOIN ga_data_aggregate d ON u.user_name = d.user_name WHERE u.department = '$department') AS a\nGROUP BY\na.submitdate, a.group_name;"
      }
     ]
    },
    {
     "title": "Contribution of groups to the carbon footprint of your department ($department)",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 320 },
     "targets": [
      {
       "rawSql": "SELECT a.group_name AS \"Group\", to_char(SUM(a.carbonfootprint)/1000, '99999') AS \"Carbon footprint (kgCO2e)\", to_char(SUM(a.cost), '99999') as \"Cost\"\nFROM\n(SELECT u.user_name, u.group_name, d.carbonfootprint, d.cost FROM ga_user u INNER JOIN ga_data_aggregate d ON u.user_name = d.user_name WHERE u.department = '$department' AND $__timeFilter(d.submitdate)) AS a\nGROUP BY a.group_name \nORDER BY a.group_name ASC;"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 328 } }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Entire institution activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 79 },
     "options": {
      "content": "## Institution\n\nOverall activity at institution in the date range specified (see date panel above)."
     }
    },
    {
     "title": "💻 CPU time",
     "type": "stat",
     "description": "Unit: weeks, months or years",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 82 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT SUM(cpuhourscharged) FROM ga_data_aggregate WHERE $__timeFilter(submitdate);\n"
      }
     ]
    },
    {
     "title": "👣  Carbon footprint ",
     "type": "stat",
     "description": "Unit: gCO2e or kgCO2e",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 82 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT SUM(carbonfootprint) FROM ga_data_aggregate WHERE $__timeFilter(submitdate);"
      }
     ]
    },
    {
     "title": "✈️  New York - San Francisco",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 8, "y": 82 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT SUM(flying_ny_sf) FROM ga_data_aggregate WHERE $__timeFilter(submitdate);"
      }
     ]
    },
    {
     "title": "✈️  Paris - London",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 13, "y": 82 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT SUM(flying_par_lon) FROM ga_data_aggregate WHERE $__timeFilter(submitdate);"
      }
     ]
    },
    {
     "title": "🌳 Carbon sequestration",
     "type": "stat",
     "description": "Unit: tree-years",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "tree-years" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT SUM(treemonths)/12 FROM ga_data_aggregate WHERE $__timeFilter(submitdate);"
      }
     ]
    },
    {
     "title": "Daily total HPC carbon footprint (all departments combined)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
     "targets": [
      {
       "rawSql": "--SELECT submitdate, SUM(carbonfootprint) AS \"Carbon footprint (gCO2e)\" FROM ga_data_aggregate GROUP BY submitdate ORDER BY submitdate ASC\n--SELECT submitdate, to_char(SUM(carbonfootprint)/1000, '99999.999') AS \"Carbon footprint (kgCO2e)\" FROM ga_data_aggregate GROUP BY submitdate ORDER BY submitdate ASC\nSELECT submitdate, SUM(carbonfootprint) AS \"Carbon footprint (gCO2e)\" FROM ga_data_aggregate GROUP BY submitdate ORDER BY submitdate ASC"
      }
     ]
    },
    {
     "title": "Daily total number of jobs submitted (all departments combined)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
     "targets": [
      {
       "rawSql": "SELECT submitdate, SUM(n_jobs) FROM ga_data_aggregate GROUP BY submitdate ORDER BY submitdate ASC;"
      }
     ]
    },
    {
     "title": "CPU core-hours (all departments combined)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
     "targets": [
      {
       "rawSql": "SELECT submitdate, SUM(cpuhourscharged) FROM ga_data_aggregate GROUP BY submitdate ORDER BY submitdate ASC "
      }
     ]
    },
    {
     "title": "Memory requested (all departments combined)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
     "targets": [
      {
       "rawSql": "SELECT submitdate, SUM(memoryrequested) FROM ga_data_aggregate GROUP BY submitdate ORDER BY submitdate ASC"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 104 } },
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 106 },
     "options": {
      "content": "### # Carbon footprint by department\n\nCarbon footprint of all departments in the time range selected (see date panel at top)."
     }
    },
    {
     "title": "Main contributors to the total carbon footprint",
     "type": "barchart",
     "description": "Carbon footprint of all departments in the time period selected (see date panel at top).\nUnit: gCO2e, kgCO2e or TCO2e",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "masskg" } },
     "targets": [
      {
       "rawSql": "SELECT a.department, SUM(a.carbonfootprint) FROM (select u.user_name, u.department, d.carbonfootprint from ga_user u INNER JOIN ga_data_aggregate d on u.user_name = d.user_name WHERE $__timeFilter(d.submitdate)) AS a GROUP BY a.department ORDER BY SUM(a.carbonfootprint) DESC;"
      }
     ]
    },
    {
     "title": "Daily carbon footprint of departments",
     "type": "timeseries",
     "description": "Unit: gCO2e or kgCO2e",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
     "targets": [
      {
       "rawSql": "SELECT a.submitdate, SUM(a.carbonfootprint) AS \"Carbon footprint of\", a.department \nFROM\n\t(SELECT d.submitdate, u.department, d.carbonfootprint \n\tFROM\n\tga_user u INNER JOIN ga_data_aggregate d ON u.user_name = d.user_name) AS a\nGROUP BY\na.submitdate, a.department;"
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 117 },
     "targets": [
      {
       "rawSql": "SELECT a.department AS \"Department\", to_char(SUM(a.carbonfootprint)/1000, '99999') AS \"Carbon footprint (kgCO2e)\", to_char(SUM(a.cost), '9999999') as \"Cost\" \nFROM (select u.user_name, u.department, d.carbonfootprint, d.cost from ga_user u INNER JOIN ga_data_aggregate d on u.user_name = d.user_name WHERE $__timeFilter(d.submitdate)) AS a GROUP BY a.department ORDER BY a.department ASC;\n"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 122 } },
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 124 },
     "options": {
      "content": "### # Efficiency metrics: Failed jobs\nBecause any resource spent on a job is wasted if the job fails, it is important to test scripts and pipelines on small datasets. The chart below\nshows the daily success and failure rates of jobs that completed in the time period selected (see date panel at top).\n\n"
     }
    },
    {
     "title": "Cost of failed jobs",
     "type": "table",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 127 },
     "targets": [
      {
       "rawSql": "SELECT SUM(n_jobs) AS \"No. of jobs submitted\", to_char(SUM(carbonfootprint_failedjobs)/1000,'99999999.99') AS \"Failed jobs' footprint (kgCO2e)\", to_char(SUM(cost_failedjobs), '9999999') AS \"Cost of failed jobs\", to_char((SUM(n_jobs-n_success)::float/SUM(n_jobs))*100, '999.99') AS \"% of failed jobs\" FROM ga_data_aggregate WHERE $__timeFilter(submitdate);"
      }
     ]
    },
    {
     "title": "Distribution Failed vs Successful jobs",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 127 },
     "targets": [
      {
       "rawSql": "SELECT submitdate, (SUM(n_jobs-n_success)::float/SUM(n_jobs))*100 AS \"Failed jobs\",  (SUM(n_success)::float/SUM(n_jobs))*100 AS \"Successful jobs\" FROM ga_data_aggregate GROUP BY submitdate ORDER BY submitdate ASC; \n"
      }
     ]
    },
    {
     "title": "Number of jobs submitted by entire institution",
     "type": "stat",
     "description": "Number of jobs (all institution) submitted by entire institution in time period selected (see date panel at top).",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 131 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT SUM(n_jobs) AS \"Number of jobs\" from ga_data_aggregate WHERE $__timeFilter(submitdate);"
      }
     ]
    },
    {
     "title": "Distribution of failed and successful jobs",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 5, "x": 7, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT SUM(n_jobs-n_success) AS \"Failed jobs\", SUM(n_success) AS \"Successful jobs\" FROM ga_data_aggregate WHERE $__timeFilter(submitdate) ORDER BY SUM(n_jobs-n_success) ASC ;"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 138 } },
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 140 },
     "options": {
      "content": "### # Memory efficiency\n\nMemory can be a significant source of waste, because the power draw from memory mainly depends on the memory available, not on the actual\nmemory used. The chart below shows the distribution of the memory efficiency (the closer to 100% the better) collected from all jobs in the time period chosen (see date panel at top)."
     }
    },
    {
     "title": "Distribution of % memory efficiency (all institution)",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 143 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT r.range as \"Memory efficiency (%)\", SUM(n_jobs) as \"Number of jobs\"\nfrom \n(\n    select '0-4' as range, 4 as endrange\n        union all select '5-9', 9\n        union all select '10-14', 14\n        union all select '15-19', 19\n        union all select '20-24', 24\n        union all select '25-29', 29\n        union all select '30-34', 34\n        union all select '35-39', 39\n        union all select '40-44', 44\n        union all select '45-49', 49\n        union all select '50-54', 54\n        union all select '55-59', 59\n        union all select '60-64', 64\n        union all select '65-69', 69\n        union all select '70-74', 74\n        union all select '75-79', 79\n        union all select '80-84', 84\n        union all select '85-89', 89\n        union all select '90-94', 94\n        union all select '95-99', 99\n        union all select '100', 100\n) as r\nleft join ga_data_aggregate on \nr.endrange = case \n    when ROUND((1/memoryoverallocationfactor)*100) = 100 then 100\n    when ROUND((1/memoryoverallocationfactor)*100) > 95 then 99\n    when ROUND((1/memoryoverallocationfactor)*100) > 90 then 94\n    when ROUND((1/memoryoverallocationfactor)*100) > 85 then 89\n    when ROUND((1/memoryoverallocationfactor)*100) > 80 then 84\n    when ROUND((1/memoryoverallocationfactor)*100) > 75 then 79\n    when ROUND((1/memoryoverallocationfactor)*100) > 70 then 74\n    when ROUND((1/memoryoverallocationfactor)*100) > 65 then 69\n    when ROUND((1/memoryoverallocationfactor)*100) > 60 then 64\n    when ROUND((1/memoryoverallocationfactor)*100) > 55 then 59\n    when ROUND((1/memoryoverallocationfactor)*100) > 50 then 54\n    when ROUND((1/memoryoverallocationfactor)*100) > 45 then 49\n    when ROUND((1/memoryoverallocationfactor)*100) > 40 then 44\n    when ROUND((1/memoryoverallocationfactor)*100) > 35 then 39\n    when ROUND((1/memoryoverallocationfactor)*100) > 30 then 34\n    when ROUND((1/memoryoverallocationfactor)*100) > 25 then 29\n    when ROUND((1/memoryoverallocationfactor)*100) > 20 then 24\n    when ROUND((1/memoryoverallocationfactor)*100) > 15 then 19\n    when ROUND((1/memoryoverallocationfactor)*100) > 10 then 14\n    when ROUND((1/memoryoverallocationfactor)*100) > 5 then 9\n    when ROUND((1/memoryoverallocationfactor)*100) >= 0 then 4\n    end\n  WHERE $__timeFilter(submitdate) \n  --WHERE user_name='${__user.login}'\n    group by r.range, r.endrange order by r.endrange;\n"
      }
     ]
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 79 } }
 ]
}