import os
import csv
import argparse

from ga_dashboard.backend.services.database_service import DBSettings, DatabaseService
from ga_dashboard.database.table_col_definitions import GA_DATA_AGGREGATE_COLUMNS, GA_USER_COLUMNS
 
"""
From Laurent

Import the aggregated mockup Slurm logs (1 entry per day and per user) into the PostgreSQL database.

The CSV files have been generated by Loïc. For the prototype, I simply wrote a script to import the files into a database (the schema is almost the same as the CSV file, with only 1 table).
 
Regarding the CSV columns documentation, I don't have one but maybe Loïc has some. I think the formats are not yet set in stone and could evolve.
However, the idea is to use a file format close to the aggregated_multi_users.csv.
 
I was waiting for the Slurm logs from CEU to write and test an import from Green Algorithms to the database.
I attached the script I used to simply import the CSV into PostgreSQL

Example:

python scripts/database/import_mockup_aggregate.py --input_log_file tests/testdata/aggregated_multi_users.csv 
    --db_user postgres --db_password <password> --db_host localhost --db_port 5432 --db_name ga_db

 user_name | submitdate | n_jobs | first_job_period | last_job_period |       energy        |     energy_cpus      | energy_gpus |    energy_memory     |
   carbonfootprint | carbonfootprint_memoryneededonly | carbonfootprint_failedjobs |     cputime     |     gputime     |  wallclocktime  |  cpuhourscharged  | gpuhourscharged |
     memoryrequested | memoryoverallocationfactor | n_success |     treemonths      | treemonths_memoryneededonly | treemonths_failedjobs |       driving       |   
        flying_ny_sf      |   flying_par_lon   |    flying_nyc_mel     |         cost         |   cost_failedjobs    | cost_memoryneededonly | success_rate | failure_rate | share_carbonfootprint 
"""


def get_columns(input_file):
    with open(input_file, newline='') as csvfile:
 
        reader = csv.DictReader(csvfile, delimiter='\t', quotechar='"')
 
        dict_from_csv = dict(list(reader)[0])
        # making a list from the keys of the dict
        return list(dict_from_csv.keys())
 

def map_column_names(file_col_names, user_data=False):
    """
    file_col_names is the list of header names in the input file.

    user_data = True if you want to use this function for 'UID', 'Name', 'Group', 'Department' and not the others
    except user_name/User   
    """
     #print(user_data)
     #print("file_col_names: " + str(file_col_names))

    db_col_names = {}
    for file_col in file_col_names:

    # Out of User, UID, Name, Group and Department we now only store User in the ga_data_aggregate table

        if user_data:
            if file_col not in ['User', 'UID', 'Name', 'Group', 'Department']:
                continue
        else:
            if file_col in ['UID', 'Name', 'Group', 'Department']:
                continue

        db_col = file_col

        db_col = db_col.lower()
        
        if db_col in ['user', 'group']:
            db_col += '_name'
        db_col_names[file_col] = db_col

    return db_col_names
 

def get_sql_command(data, columns):
    values = []
    for col in columns:
        value = data[col]
        if type(value) is str:
            values.append(f"'{data[col]}'")
        else:
            values.append(str(data[col]))
    return ','.join(values)
 

def parse_string_to_number(s):
    try:
        return int(s)
    except ValueError:
        try:
            return float(s)
        except ValueError:
            return None
 

def main():
 
    argparser = argparse.ArgumentParser(description="Import some mock aggregated data into the database.")
    argparser.add_argument("--input_log_file", help='Logs data', required=True, metavar='INPUT_FILE')
    argparser.add_argument("--db_name", help='Database name', required=True, metavar='DBNAME',default='ga_db')
    argparser.add_argument("--db_user", help='Database user name', required=True, metavar='DBUSER')
    argparser.add_argument("--db_password", help='Database user password', required=True, metavar='DBPASS')
    argparser.add_argument("--db_host", help='Database host', required=True, metavar='DBHOST',default='localhost')
    argparser.add_argument("--db_port", help='Database port', required=True, metavar='DBPORT',default=5432)
 
    args = argparser.parse_args()
 
    input_file = args.input_log_file
    db_settings = DBSettings(
        db_name=args.db_name,
        user=args.db_user,
        password=args.db_password,
        host=args.db_host,
        port=args.db_port
    )
 
    if not os.path.isfile(input_file):
        print(f"File '{input_file}' can't be found")
        exit(1)
 
    # Prepare DB column names from the ones in the input file:
    raw_column_names = get_columns(input_file)
    db_column_names_mapping = map_column_names(raw_column_names)
    db_column_names = list(db_column_names_mapping.values())

    # Now do the same for the user's institutional information:
    #raw_column_names = get_columns(input_file)
    user_db_column_names_mapping = map_column_names(raw_column_names, user_data=True)
    user_db_column_names = list(user_db_column_names_mapping.values())

    data_rows = []
    user_rows = []
 
    with open(input_file, newline='') as csvfile:
        reader = csv.DictReader(csvfile, delimiter='\t', quotechar='"')
        for row in reader:
            # Aggregate data
            data_row = {}
            for col in raw_column_names:
                if col in ['UID', 'Name', 'Group', 'Department']:
                    continue
                db_col = db_column_names_mapping[col]
                value = row[col]
                new_value = parse_string_to_number(value)
                if new_value is not None:
                    value = new_value
                if db_col == 'state_x':
                    value = True if value == 1 else False
                data_row[db_col] = value
            data_rows.append(data_row)

            # Now extract the user data
            # user db col names mapping is: 
            # {'User': 'user_name', 'UID': 'uid', 'Name': 'name', 'Group': 'group', 'Department': 'department'}
            user_data_row = {}
            for col in raw_column_names:
                if col not in ['User', 'UID', 'Name', 'Group', 'Department']:
                    continue
                db_col = user_db_column_names_mapping[col]
                value = row[col]
                new_value = parse_string_to_number(value)
                if new_value is not None:
                    value = new_value
                user_data_row[db_col] = value
            user_rows.append(user_data_row)

    # Use DatabaseService for bulk inserts
    with DatabaseService(db_settings) as database:
        if not database.is_conn_ok():
            print('DB connection error. Exiting...')
            exit(1)

        # Insert aggregate data in batches
        database.bulk_insert_data(
            table_name="ga_data_aggregate",
            columns=db_column_names,
            rows=data_rows,
            on_conflict="DO NOTHING",
            batch_size=1000
        )

        # Insert user data in batches
        database.bulk_insert_data(
            table_name="ga_user",
            columns=user_db_column_names,
            rows=user_rows,
            on_conflict="DO NOTHING",
            batch_size=500
        )

    print("Script completed successfully.")
 
if __name__ == '__main__':
    main()
 
 